apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-rs
  namespace: demo
spec:
  version: "3.4"
  replicas: 3
  clusterMode:
    replicaSet:
      name: rs15
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi