apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-rs0
  namespace: demo
spec:
  version: "3.6"
  replicas: 3
  clusterMode:
    replicaSet:
      name: rs0
  storage:
#    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
